### ISSUE TITLE
error on compile

### ISSUE THREAD

**Issue by HaxorGaruda** [ctxis/yate-bts#1]
when i compile .. get error like this : 
`MSInfo.cpp:641:86: error: no match for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}’)
             GPRSLOG(INFO,GPRS_MSG|GPRS_CHECK_OK) << "Multislot assignment for "<<this<<os;
                                                                                       
MSInfo.cpp:641:86: note: candidate: operator<<(int, int) <built-in>
MSInfo.cpp:641:86: note:   no known conversion for argument 2 from ‘std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}’ to ‘int’
In file included from /usr/include/c++/6/iostream:39:0,
                 from ./../CommonLibs/Timeval.h:31,
                 from ./../CommonLibs/Interthread.h:29,
                 from MSInfo.h:19,
                 from MSInfo.cpp:17:
/usr/include/c++/6/ostream:108:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__ostream_type& (*)(std::basic_ostream<_CharT, _Traits>::__ostream_type&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(__ostream_type& (*__pf)(__ostream_type&))
       ^~~~~~~~
/usr/include/c++/6/ostream:108:7: note:   no known conversion for argument 1 from ‘std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}’ to ‘std::basic_ostream<char>::__ostream_type& (*)(std::basic_ostream<char>::__ostream_type&) {aka std::basic_ostream<char>& (*)(std::basic_ostream<char>&)}’
/usr/include/c++/6/ostream:117:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__ios_type& (*)(std::basic_ostream<_CharT, _Traits>::__ios_type&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>; std::basic_ostream<_CharT, _Traits>::__ios_type = std::basic_ios<char>]
       operator<<(__ios_type& (*__pf)(__ios_type&))
`

**Comment by HaxorGaruda** [comment]
sorry.. this error cause version of GCC 6, i change to GCC 5 and compile success ... thanks

**Comment by lincolnq** [comment]
I also ran into this. On Ubuntu Artful, I fixed it by switching to g++ 5 as above commenter suggested. Specifically:

```
sudo apt install g++-5
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
```

**Comment by scaery** [comment]
Solution:
https://forum.yate.ro/index.php?topic=1966.0

Just fix em by adding str()
